In [2]:
import pandas as pd

In [3]:
data = {
    "Name" : ["Saransh","Humera","Abhi"],
    "Age" : [20,21,23],
    "Marks" : [78,100,65]
}

pd.DataFrame(data)

      Name  Age  Marks
0  Saransh   20     78
1   Humera   21    100
2     Abhi   23     65

In [4]:
# list into dataframe :- 
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)

# writing column name manually 
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
# to access only Name and Age 
df2[["Name","Salary"]]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [6]:
# creating a new column
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [7]:
# to removing the column
df2.drop("Designation",axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2 # designation is still there

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [ ]:
# for deleting the designation permanentaly
df2.drop("Designation",axis = 1,inplace=True)
df2 # now Designation is deleted permanantly

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# conditional selection 
# i only want to print only student whose age is greater than 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [16]:
# i only want to print only student whose age is greater than 30 and belongs from paris
df2[ (df2["Age"] > 30)  & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000