In [8]:
import numpy as np
import pandas as pd

In [9]:
# data
# nan - not a number
data = {
    'A' : [1,2,np.nan,4,5],
    'B' : [1,2,3,4,5],
    'C' : [1,2,3,np.nan,np.nan],
    'D' : [1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
# how to find the missing data
# print the boolean indexing of the data where nan is present it show True
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [11]:
# count the nan value
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
# remove the missing data , when the nan is there it removes 
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
# thresh = when you use it we need to provide one value like (thresh = n) here n = non null value 
# here n = 3 means whoever row has 3 non null value it will printed
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [14]:
# here n = 4
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [16]:
# fill the missing data where the value is nan we need to fill those value
df.fillna(0) # it fill the value with 0 where nan present

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [20]:
# this block of code will fill the value with particular value like if A column have nan value i fill with 0
# same for B have nan value it fill with 100, for C = 300, for D = 400
values = {
    'A' : 0,
    'B' : 100,
    'C' : 300,
    'D' : 400
}
values
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0