In [32]:
import numpy as np
import pandas as pd

In [ ]:
# merge the two data frames

# data frame 1 :-
employees = pd.DataFrame({
    'Employee_id' : [1,2,3,4,5],
    'name' : ['John','Bob','Alice','Hary','Sam'],
    'department' :['HR','IT','Finance','Analytics','CA']
})

# data frame 2 :
salaries = pd.DataFrame({
    'Employee_id' : [1,2,3,6,7],
    'salary' : [10000,20000,30000,40000,50000],
    'bonus' : [3000,2000,4000,1000,5000]
})

In [34]:
employees

   Employee_id   name department
0            1   John         HR
1            2    Bob         IT
2            3  Alice    Finance
3            4   Hary  Analytics
4            5    Sam         CA

In [35]:
salaries

   Employee_id  salary  bonus
0            1   10000   3000
1            2   20000   2000
2            3   30000   4000
3            6   40000   1000
4            7   50000   5000

In [36]:
# merge both the dataframe
# Note :- merging will happen on the basis of something common like here Employee_id is common
pd.merge(employees,salaries,on='Employee_id',how='inner')

# on - means on the basis of employee_id 
# how = 'inner' - means join this by inner like the common of both data frames

   Employee_id   name department  salary  bonus
0            1   John         HR   10000   3000
1            2    Bob         IT   20000   2000
2            3  Alice    Finance   30000   4000

In [38]:
pd.merge(employees,salaries,on='Employee_id',how='outer')

# how = outer - means it join both the data frame without intersection like the union of the both data frame

   Employee_id   name department   salary   bonus
0            1   John         HR  10000.0  3000.0
1            2    Bob         IT  20000.0  2000.0
2            3  Alice    Finance  30000.0  4000.0
3            4   Hary  Analytics      NaN     NaN
4            5    Sam         CA      NaN     NaN
5            6    NaN        NaN  40000.0  1000.0
6            7    NaN        NaN  50000.0  5000.0

In [ ]:
# how = left - means merge on the basis of employees
pd.merge(employees,salaries,on='Employee_id',how='left')

   Employee_id   name department   salary   bonus
0            1   John         HR  10000.0  3000.0
1            2    Bob         IT  20000.0  2000.0
2            3  Alice    Finance  30000.0  4000.0
3            4   Hary  Analytics      NaN     NaN
4            5    Sam         CA      NaN     NaN

In [ ]:
# how = right - means merge on the basis of salaries
pd.merge(employees,salaries,on='Employee_id',how='right')

   Employee_id   name department  salary  bonus
0            1   John         HR   10000   3000
1            2    Bob         IT   20000   2000
2            3  Alice    Finance   30000   4000
3            6    NaN        NaN   40000   1000
4            7    NaN        NaN   50000   5000

In [ ]:
# concatenate
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B': ['B0','B1','B2'],
    'C': ['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B': ['B3','B4','B5'],
    'C': ['C3','C4','C5']
})

# concate on the basis of column
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [47]:
# concate on the basis of rows
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
# joining two data frame
df3 = pd.DataFrame({
    'name':['Alice','Bob','Charlie'],
},  
    index=[1,2,3]
)

df4 = pd.DataFrame({
    'score' : [85,90,75],
}, index=[2,3,4])

df3.join(df4)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0