In [19]:
import numpy as np
import pandas as pd

In [20]:
# merge the two data frames

# data frame 1 :-
employees = pd.DataFrame({
    'Employee_id' : [1,2,3,4,5],
    'name' : ['John','Bob','Alice','Hary','Sam'],
    'department' :['HR','IT','Finance','Analytics','CA']
})

# data frame 2 :
salaries = pd.DataFrame({
    'Employee_id' : [1,2,3,6,7],
    'salary' : [10000,20000,30000,40000,50000],
    'bonus' : [3000,2000,4000,1000,5000]
})

In [21]:
employees

   Employee_id   name department
0            1   John         HR
1            2    Bob         IT
2            3  Alice    Finance
3            4   Hary  Analytics
4            5    Sam         CA

In [22]:
salaries

   Employee_id  salary  bonus
0            1   10000   3000
1            2   20000   2000
2            3   30000   4000
3            6   40000   1000
4            7   50000   5000

In [23]:
# merge both the dataframe
# Note :- merging will happen on the basis of something common like here Employee_id is common
pd.merge(employees,salaries)

   Employee_id   name department  salary  bonus
0            1   John         HR   10000   3000
1            2    Bob         IT   20000   2000
2            3  Alice    Finance   30000   4000